# Generated by Django 5.2 on 2025-04-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotluckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('Group 1', 'Group 1'), ('Group 2', 'Group 2'), ('Group 3', 'Group 3'), ('Group 4', 'Group 4'), ('Group 5', 'Group 5'), ('Group 6', 'Group 6')], max_length=10, verbose_name='Your Assigned Group')),
                ('category', models.CharField(choices=[('Entrée', 'Entrée'), ('Sides', 'Sides'), ('Desserts', 'Desserts'), ('Drinks/Utensils', 'Drinks/Utensils')], max_length=20)),
                ('item_description', models.TextField(verbose_name='What are you bringing?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Potluck Item',
                'verbose_name_plural': 'Potluck Items',
                'ordering': ['category', 'submitted_at'],
            },
        ),
    ]
