# Generated by Django 5.2 on 2025-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potluckitem',
            name='submitter_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Your Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potluckitem',
            name='submitter_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Your Phone Number (Optional)'),
        ),
        migrations.AlterField(
            model_name='potluckitem',
            name='group_name',
            field=models.CharField(choices=[('Family A', 'Family A (Entrée)'), ('Team Awesome', 'Team Awesome (Entrée)'), ('The Foodies', 'The Foodies (Sides)'), ('Neighbors', 'Neighbors (Sides)'), ('Sweet Tooth Crew', 'Sweet Tooth Crew (Desserts)'), ('Drink Masters', 'Drink Masters (Drinks/Utensils)')], max_length=50, verbose_name='Your Assigned Group'),
        ),
    ]
